### ISSUE TITLE
How to import html as string ?

### ISSUE THREAD

**Issue by Yunlong2cn** [brandonroberts/angular2-router-example#1]
Hi,i have seen this app and found
```
import template from "./home.html"
```
but i use it in my app and compile errors
```
TypeScript error: src/app/pages/home/home.ts(8,22): Error TS2307: Cannot find module './home.html'.
```
how to solve it?

**Comment by brandonroberts** [comment]
@Yunlong2cn the html as string is done in the build process. I use browserify to bundle up the application and the plugin is named [stringify](https://github.com/JohnPostlethwait/stringify).

You can see it in my gulpfile 

https://github.com/brandonroberts/angular2-router-example/blob/master/gulpfile.js#L24

**Comment by Yunlong2cn** [comment]
@brandonroberts oh,yes,thanks and i had tried stringify yesterday,but it not works,this is my gulpfile.js
```
gulp.task('tsify', function() {
	var bundler = browserify({baseDir: 'src/app', debug: true})
		.transform(stringify(['.html']))
		.add('src/app/app.ts')
		.plugin(tsify, tsConfig);

	return bundler.bundle()
		.on('error', function (error) { console.error(error.toString()); })
		.pipe(source('app.js'))
		.pipe(streamify(uglify()))
		.pipe(gulp.dest('dist/js'));
});
```
then gulp tsify and show me 

```
TypeScript error: src/app/pages/home/home.ts(9,22): Error TS2307: Cannot find module './home.html'.
```

**Comment by brandonroberts** [comment]
@Yunlong2cn using tsify on its own does not support importing html templates that way. See https://github.com/TypeStrong/tsify/issues/88
