### ISSUE TITLE
Nested routing problem !!!!

### ISSUE THREAD

**Issue by alaa-bourouissi** [brandonroberts/angular2-router-example#5]
hello @brandonroberts please can you help me in this problem , so i'm using the ng2-bootstrap w template based on angular 2 , i have created a component called TableCompoent.ts and added it to the routes . I have also created another component called DetailsComponent.ts , this component is a child of the TableComponent.ts , so in the routes i added : 

## the config.ts : 

export const routes:RouterConfig = [
  {
    path: 'Table',
    component: TableComponent,
    children: [
      {
        path: 'Details',
        component: DetailsTableComponent,
      }
    ]
  },
  {
    path: 'Forms',
    data: ['Forms'],
    component: FormsComponent,
  },
  {
    path: 'Charts',
    data: ['Charts'],
    component: ChartComponent,
  },.........
export const APP_ROUTER_PROVIDERS = [
  provideRouter(routes)
];

## in the TableComponent.ts : 
let template = require('./TableComponent.html');
@Component({
  selector: 'table-component',
  template: template,
  directives: [ROUTER_DIRECTIVES]
})
export  class TableComponent {

  public cursens:Array<any> = TableData;
}
## in the TableComponent.html: 
.......
.........
< a [routerLink]="['Table/Details']" >Contact< /a >
< router-outlet >< /router-outlet >

The problem in when i click on the link of the Table , i should be redirect to localhost:3000/Table , in this view it's expected to find another lnk that redirect me to te DetailsComponent localhost:3000/Table/Details , but when i click on the Table link it goes to the root lik localhost:3000/ not the TableComponent and also when i tape the url in the browser localhost:3000/Table it redirect me also to the localhost:3000/ , another issue is that when i tape the url localhost:3000/Table/Details i found in this view the template of the TableComponent and DetailsComponent with each other (in the top the table of the TableComponent.html) and in the bottom (the label of the DetailsComponent.html ), and in the console of the browser and the terminal there is no problem or errors !!!!!!

please @brandonroberts  can you help me in this problem , I've been in this problem for 5 days and nothing found that can help me !!!!

**Comment by brandonroberts** [comment]
@alaa-bourouissi do you have a repo available to share?

**Comment by alaa-bourouissi** [comment]
@brandonroberts  please can you explain what de you mean by repo ?

**Comment by brandonroberts** [comment]
Do you have your code somewhere I can see it like on Github?

**Comment by alaa-bourouissi** [comment]
i'm new here @brandonroberts , can i send you my code somewhere (exp your mail ..) ??

**Comment by brandonroberts** [comment]
Why don't you come in the gitter support channel at http://gitter.im/angular/angular and we can help you there. Just add my name (@brandonroberts) to your message

**Comment by FarhodKurbonov** [comment]
Good example. I was wrote issue: https://github.com/angular/angular/issues/7641 where you recommend genereate instruction for retrieve data from routeConfig. But can in new version of "@angular/router": "3.0.0-beta.2" there is no method 'generate' Can you help resove this issue. Thank you!
