### ISSUE TITLE
Generate Instruction 

### ISSUE THREAD

**Issue by FarhodKurbonov** [brandonroberts/angular2-router-example#6]
I was wrote issue: angular/angular#7641 where you recommend genereate instruction for retrieve data from routeConfig. In this example you also use "generate" method for create instruction.  But in new version of "@angular/router": "3.0.0-beta.2" there is no method 'generate' Can you help resove this issue. Thank you!

**Comment by brandonroberts** [comment]
The method in the new router is `router.createUrlTree` that you can use with the same syntax you use for a routerLink
